package defpackage;

import com.google.android.gms.common.api.Status;

public class abg<R extends xc> extends xa<R> {
    private final Status a;

    public Integer a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void a(xd<? super R> xdVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status b() {
        return this.a;
    }
}
