/*
 * Decompiled with CFR 0_110.
 * 
 * Could not load the following classes:
 *  com.google.android.gms.common.api.Status
 *  java.lang.Integer
 *  java.lang.String
 *  java.lang.UnsupportedOperationException
 */
import com.google.android.gms.common.api.Status;

public class abg<R extends xc>
extends xa<R> {
    private final Status a;

    @Override
    public Integer a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override
    public void a(xd<? super R> xd2) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status b() {
        return this.a;
    }
}

