/*
 * Decompiled with CFR 0_110.
 * 
 * Could not load the following classes:
 *  java.lang.Integer
 *  java.lang.Object
 *  java.lang.String
 *  java.util.ArrayList
 *  java.util.HashMap
 *  java.util.List
 *  java.util.Map
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ajq {
    public static Map<Integer, List<String>> a() {
        HashMap hashMap = new HashMap(285);
        ArrayList arrayList = new ArrayList(25);
        arrayList.add((Object)"US");
        arrayList.add((Object)"AG");
        arrayList.add((Object)"AI");
        arrayList.add((Object)"AS");
        arrayList.add((Object)"BB");
        arrayList.add((Object)"BM");
        arrayList.add((Object)"BS");
        arrayList.add((Object)"CA");
        arrayList.add((Object)"DM");
        arrayList.add((Object)"DO");
        arrayList.add((Object)"GD");
        arrayList.add((Object)"GU");
        arrayList.add((Object)"JM");
        arrayList.add((Object)"KN");
        arrayList.add((Object)"KY");
        arrayList.add((Object)"LC");
        arrayList.add((Object)"MP");
        arrayList.add((Object)"MS");
        arrayList.add((Object)"PR");
        arrayList.add((Object)"SX");
        arrayList.add((Object)"TC");
        arrayList.add((Object)"TT");
        arrayList.add((Object)"VC");
        arrayList.add((Object)"VG");
        arrayList.add((Object)"VI");
        hashMap.put((Object)1, (Object)arrayList);
        ArrayList arrayList2 = new ArrayList(2);
        arrayList2.add((Object)"RU");
        arrayList2.add((Object)"KZ");
        hashMap.put((Object)7, (Object)arrayList2);
        ArrayList arrayList3 = new ArrayList(1);
        arrayList3.add((Object)"EG");
        hashMap.put((Object)20, (Object)arrayList3);
        ArrayList arrayList4 = new ArrayList(1);
        arrayList4.add((Object)"ZA");
        hashMap.put((Object)27, (Object)arrayList4);
        ArrayList arrayList5 = new ArrayList(1);
        arrayList5.add((Object)"GR");
        hashMap.put((Object)30, (Object)arrayList5);
        ArrayList arrayList6 = new ArrayList(1);
        arrayList6.add((Object)"NL");
        hashMap.put((Object)31, (Object)arrayList6);
        ArrayList arrayList7 = new ArrayList(1);
        arrayList7.add((Object)"BE");
        hashMap.put((Object)32, (Object)arrayList7);
        ArrayList arrayList8 = new ArrayList(1);
        arrayList8.add((Object)"FR");
        hashMap.put((Object)33, (Object)arrayList8);
        ArrayList arrayList9 = new ArrayList(1);
        arrayList9.add((Object)"ES");
        hashMap.put((Object)34, (Object)arrayList9);
        ArrayList arrayList10 = new ArrayList(1);
        arrayList10.add((Object)"HU");
        hashMap.put((Object)36, (Object)arrayList10);
        ArrayList arrayList11 = new ArrayList(2);
        arrayList11.add((Object)"IT");
        arrayList11.add((Object)"VA");
        hashMap.put((Object)39, (Object)arrayList11);
        ArrayList arrayList12 = new ArrayList(1);
        arrayList12.add((Object)"RO");
        hashMap.put((Object)40, (Object)arrayList12);
        ArrayList arrayList13 = new ArrayList(1);
        arrayList13.add((Object)"CH");
        hashMap.put((Object)41, (Object)arrayList13);
        ArrayList arrayList14 = new ArrayList(1);
        arrayList14.add((Object)"AT");
        hashMap.put((Object)43, (Object)arrayList14);
        ArrayList arrayList15 = new ArrayList(4);
        arrayList15.add((Object)"GB");
        arrayList15.add((Object)"GG");
        arrayList15.add((Object)"IM");
        arrayList15.add((Object)"JE");
        hashMap.put((Object)44, (Object)arrayList15);
        ArrayList arrayList16 = new ArrayList(1);
        arrayList16.add((Object)"DK");
        hashMap.put((Object)45, (Object)arrayList16);
        ArrayList arrayList17 = new ArrayList(1);
        arrayList17.add((Object)"SE");
        hashMap.put((Object)46, (Object)arrayList17);
        ArrayList arrayList18 = new ArrayList(2);
        arrayList18.add((Object)"NO");
        arrayList18.add((Object)"SJ");
        hashMap.put((Object)47, (Object)arrayList18);
        ArrayList arrayList19 = new ArrayList(1);
        arrayList19.add((Object)"PL");
        hashMap.put((Object)48, (Object)arrayList19);
        ArrayList arrayList20 = new ArrayList(1);
        arrayList20.add((Object)"DE");
        hashMap.put((Object)49, (Object)arrayList20);
        ArrayList arrayList21 = new ArrayList(1);
        arrayList21.add((Object)"PE");
        hashMap.put((Object)51, (Object)arrayList21);
        ArrayList arrayList22 = new ArrayList(1);
        arrayList22.add((Object)"MX");
        hashMap.put((Object)52, (Object)arrayList22);
        ArrayList arrayList23 = new ArrayList(1);
        arrayList23.add((Object)"CU");
        hashMap.put((Object)53, (Object)arrayList23);
        ArrayList arrayList24 = new ArrayList(1);
        arrayList24.add((Object)"AR");
        hashMap.put((Object)54, (Object)arrayList24);
        ArrayList arrayList25 = new ArrayList(1);
        arrayList25.add((Object)"BR");
        hashMap.put((Object)55, (Object)arrayList25);
        ArrayList arrayList26 = new ArrayList(1);
        arrayList26.add((Object)"CL");
        hashMap.put((Object)56, (Object)arrayList26);
        ArrayList arrayList27 = new ArrayList(1);
        arrayList27.add((Object)"CO");
        hashMap.put((Object)57, (Object)arrayList27);
        ArrayList arrayList28 = new ArrayList(1);
        arrayList28.add((Object)"VE");
        hashMap.put((Object)58, (Object)arrayList28);
        ArrayList arrayList29 = new ArrayList(1);
        arrayList29.add((Object)"MY");
        hashMap.put((Object)60, (Object)arrayList29);
        ArrayList arrayList30 = new ArrayList(3);
        arrayList30.add((Object)"AU");
        arrayList30.add((Object)"CC");
        arrayList30.add((Object)"CX");
        hashMap.put((Object)61, (Object)arrayList30);
        ArrayList arrayList31 = new ArrayList(1);
        arrayList31.add((Object)"ID");
        hashMap.put((Object)62, (Object)arrayList31);
        ArrayList arrayList32 = new ArrayList(1);
        arrayList32.add((Object)"PH");
        hashMap.put((Object)63, (Object)arrayList32);
        ArrayList arrayList33 = new ArrayList(1);
        arrayList33.add((Object)"NZ");
        hashMap.put((Object)64, (Object)arrayList33);
        ArrayList arrayList34 = new ArrayList(1);
        arrayList34.add((Object)"SG");
        hashMap.put((Object)65, (Object)arrayList34);
        ArrayList arrayList35 = new ArrayList(1);
        arrayList35.add((Object)"TH");
        hashMap.put((Object)66, (Object)arrayList35);
        ArrayList arrayList36 = new ArrayList(1);
        arrayList36.add((Object)"JP");
        hashMap.put((Object)81, (Object)arrayList36);
        ArrayList arrayList37 = new ArrayList(1);
        arrayList37.add((Object)"KR");
        hashMap.put((Object)82, (Object)arrayList37);
        ArrayList arrayList38 = new ArrayList(1);
        arrayList38.add((Object)"VN");
        hashMap.put((Object)84, (Object)arrayList38);
        ArrayList arrayList39 = new ArrayList(1);
        arrayList39.add((Object)"CN");
        hashMap.put((Object)86, (Object)arrayList39);
        ArrayList arrayList40 = new ArrayList(1);
        arrayList40.add((Object)"TR");
        hashMap.put((Object)90, (Object)arrayList40);
        ArrayList arrayList41 = new ArrayList(1);
        arrayList41.add((Object)"IN");
        hashMap.put((Object)91, (Object)arrayList41);
        ArrayList arrayList42 = new ArrayList(1);
        arrayList42.add((Object)"PK");
        hashMap.put((Object)92, (Object)arrayList42);
        ArrayList arrayList43 = new ArrayList(1);
        arrayList43.add((Object)"AF");
        hashMap.put((Object)93, (Object)arrayList43);
        ArrayList arrayList44 = new ArrayList(1);
        arrayList44.add((Object)"LK");
        hashMap.put((Object)94, (Object)arrayList44);
        ArrayList arrayList45 = new ArrayList(1);
        arrayList45.add((Object)"MM");
        hashMap.put((Object)95, (Object)arrayList45);
        ArrayList arrayList46 = new ArrayList(1);
        arrayList46.add((Object)"IR");
        hashMap.put((Object)98, (Object)arrayList46);
        ArrayList arrayList47 = new ArrayList(1);
        arrayList47.add((Object)"SS");
        hashMap.put((Object)211, (Object)arrayList47);
        ArrayList arrayList48 = new ArrayList(2);
        arrayList48.add((Object)"MA");
        arrayList48.add((Object)"EH");
        hashMap.put((Object)212, (Object)arrayList48);
        ArrayList arrayList49 = new ArrayList(1);
        arrayList49.add((Object)"DZ");
        hashMap.put((Object)213, (Object)arrayList49);
        ArrayList arrayList50 = new ArrayList(1);
        arrayList50.add((Object)"TN");
        hashMap.put((Object)216, (Object)arrayList50);
        ArrayList arrayList51 = new ArrayList(1);
        arrayList51.add((Object)"LY");
        hashMap.put((Object)218, (Object)arrayList51);
        ArrayList arrayList52 = new ArrayList(1);
        arrayList52.add((Object)"GM");
        hashMap.put((Object)220, (Object)arrayList52);
        ArrayList arrayList53 = new ArrayList(1);
        arrayList53.add((Object)"SN");
        hashMap.put((Object)221, (Object)arrayList53);
        ArrayList arrayList54 = new ArrayList(1);
        arrayList54.add((Object)"MR");
        hashMap.put((Object)222, (Object)arrayList54);
        ArrayList arrayList55 = new ArrayList(1);
        arrayList55.add((Object)"ML");
        hashMap.put((Object)223, (Object)arrayList55);
        ArrayList arrayList56 = new ArrayList(1);
        arrayList56.add((Object)"GN");
        hashMap.put((Object)224, (Object)arrayList56);
        ArrayList arrayList57 = new ArrayList(1);
        arrayList57.add((Object)"CI");
        hashMap.put((Object)225, (Object)arrayList57);
        ArrayList arrayList58 = new ArrayList(1);
        arrayList58.add((Object)"BF");
        hashMap.put((Object)226, (Object)arrayList58);
        ArrayList arrayList59 = new ArrayList(1);
        arrayList59.add((Object)"NE");
        hashMap.put((Object)227, (Object)arrayList59);
        ArrayList arrayList60 = new ArrayList(1);
        arrayList60.add((Object)"TG");
        hashMap.put((Object)228, (Object)arrayList60);
        ArrayList arrayList61 = new ArrayList(1);
        arrayList61.add((Object)"BJ");
        hashMap.put((Object)229, (Object)arrayList61);
        ArrayList arrayList62 = new ArrayList(1);
        arrayList62.add((Object)"MU");
        hashMap.put((Object)230, (Object)arrayList62);
        ArrayList arrayList63 = new ArrayList(1);
        arrayList63.add((Object)"LR");
        hashMap.put((Object)231, (Object)arrayList63);
        ArrayList arrayList64 = new ArrayList(1);
        arrayList64.add((Object)"SL");
        hashMap.put((Object)232, (Object)arrayList64);
        ArrayList arrayList65 = new ArrayList(1);
        arrayList65.add((Object)"GH");
        hashMap.put((Object)233, (Object)arrayList65);
        ArrayList arrayList66 = new ArrayList(1);
        arrayList66.add((Object)"NG");
        hashMap.put((Object)234, (Object)arrayList66);
        ArrayList arrayList67 = new ArrayList(1);
        arrayList67.add((Object)"TD");
        hashMap.put((Object)235, (Object)arrayList67);
        ArrayList arrayList68 = new ArrayList(1);
        arrayList68.add((Object)"CF");
        hashMap.put((Object)236, (Object)arrayList68);
        ArrayList arrayList69 = new ArrayList(1);
        arrayList69.add((Object)"CM");
        hashMap.put((Object)237, (Object)arrayList69);
        ArrayList arrayList70 = new ArrayList(1);
        arrayList70.add((Object)"CV");
        hashMap.put((Object)238, (Object)arrayList70);
        ArrayList arrayList71 = new ArrayList(1);
        arrayList71.add((Object)"ST");
        hashMap.put((Object)239, (Object)arrayList71);
        ArrayList arrayList72 = new ArrayList(1);
        arrayList72.add((Object)"GQ");
        hashMap.put((Object)240, (Object)arrayList72);
        ArrayList arrayList73 = new ArrayList(1);
        arrayList73.add((Object)"GA");
        hashMap.put((Object)241, (Object)arrayList73);
        ArrayList arrayList74 = new ArrayList(1);
        arrayList74.add((Object)"CG");
        hashMap.put((Object)242, (Object)arrayList74);
        ArrayList arrayList75 = new ArrayList(1);
        arrayList75.add((Object)"CD");
        hashMap.put((Object)243, (Object)arrayList75);
        ArrayList arrayList76 = new ArrayList(1);
        arrayList76.add((Object)"AO");
        hashMap.put((Object)244, (Object)arrayList76);
        ArrayList arrayList77 = new ArrayList(1);
        arrayList77.add((Object)"GW");
        hashMap.put((Object)245, (Object)arrayList77);
        ArrayList arrayList78 = new ArrayList(1);
        arrayList78.add((Object)"IO");
        hashMap.put((Object)246, (Object)arrayList78);
        ArrayList arrayList79 = new ArrayList(1);
        arrayList79.add((Object)"AC");
        hashMap.put((Object)247, (Object)arrayList79);
        ArrayList arrayList80 = new ArrayList(1);
        arrayList80.add((Object)"SC");
        hashMap.put((Object)248, (Object)arrayList80);
        ArrayList arrayList81 = new ArrayList(1);
        arrayList81.add((Object)"SD");
        hashMap.put((Object)249, (Object)arrayList81);
        ArrayList arrayList82 = new ArrayList(1);
        arrayList82.add((Object)"RW");
        hashMap.put((Object)250, (Object)arrayList82);
        ArrayList arrayList83 = new ArrayList(1);
        arrayList83.add((Object)"ET");
        hashMap.put((Object)251, (Object)arrayList83);
        ArrayList arrayList84 = new ArrayList(1);
        arrayList84.add((Object)"SO");
        hashMap.put((Object)252, (Object)arrayList84);
        ArrayList arrayList85 = new ArrayList(1);
        arrayList85.add((Object)"DJ");
        hashMap.put((Object)253, (Object)arrayList85);
        ArrayList arrayList86 = new ArrayList(1);
        arrayList86.add((Object)"KE");
        hashMap.put((Object)254, (Object)arrayList86);
        ArrayList arrayList87 = new ArrayList(1);
        arrayList87.add((Object)"TZ");
        hashMap.put((Object)255, (Object)arrayList87);
        ArrayList arrayList88 = new ArrayList(1);
        arrayList88.add((Object)"UG");
        hashMap.put((Object)256, (Object)arrayList88);
        ArrayList arrayList89 = new ArrayList(1);
        arrayList89.add((Object)"BI");
        hashMap.put((Object)257, (Object)arrayList89);
        ArrayList arrayList90 = new ArrayList(1);
        arrayList90.add((Object)"MZ");
        hashMap.put((Object)258, (Object)arrayList90);
        ArrayList arrayList91 = new ArrayList(1);
        arrayList91.add((Object)"ZM");
        hashMap.put((Object)260, (Object)arrayList91);
        ArrayList arrayList92 = new ArrayList(1);
        arrayList92.add((Object)"MG");
        hashMap.put((Object)261, (Object)arrayList92);
        ArrayList arrayList93 = new ArrayList(2);
        arrayList93.add((Object)"RE");
        arrayList93.add((Object)"YT");
        hashMap.put((Object)262, (Object)arrayList93);
        ArrayList arrayList94 = new ArrayList(1);
        arrayList94.add((Object)"ZW");
        hashMap.put((Object)263, (Object)arrayList94);
        ArrayList arrayList95 = new ArrayList(1);
        arrayList95.add((Object)"NA");
        hashMap.put((Object)264, (Object)arrayList95);
        ArrayList arrayList96 = new ArrayList(1);
        arrayList96.add((Object)"MW");
        hashMap.put((Object)265, (Object)arrayList96);
        ArrayList arrayList97 = new ArrayList(1);
        arrayList97.add((Object)"LS");
        hashMap.put((Object)266, (Object)arrayList97);
        ArrayList arrayList98 = new ArrayList(1);
        arrayList98.add((Object)"BW");
        hashMap.put((Object)267, (Object)arrayList98);
        ArrayList arrayList99 = new ArrayList(1);
        arrayList99.add((Object)"SZ");
        hashMap.put((Object)268, (Object)arrayList99);
        ArrayList arrayList100 = new ArrayList(1);
        arrayList100.add((Object)"KM");
        hashMap.put((Object)269, (Object)arrayList100);
        ArrayList arrayList101 = new ArrayList(2);
        arrayList101.add((Object)"SH");
        arrayList101.add((Object)"TA");
        hashMap.put((Object)290, (Object)arrayList101);
        ArrayList arrayList102 = new ArrayList(1);
        arrayList102.add((Object)"ER");
        hashMap.put((Object)291, (Object)arrayList102);
        ArrayList arrayList103 = new ArrayList(1);
        arrayList103.add((Object)"AW");
        hashMap.put((Object)297, (Object)arrayList103);
        ArrayList arrayList104 = new ArrayList(1);
        arrayList104.add((Object)"FO");
        hashMap.put((Object)298, (Object)arrayList104);
        ArrayList arrayList105 = new ArrayList(1);
        arrayList105.add((Object)"GL");
        hashMap.put((Object)299, (Object)arrayList105);
        ArrayList arrayList106 = new ArrayList(1);
        arrayList106.add((Object)"GI");
        hashMap.put((Object)350, (Object)arrayList106);
        ArrayList arrayList107 = new ArrayList(1);
        arrayList107.add((Object)"PT");
        hashMap.put((Object)351, (Object)arrayList107);
        ArrayList arrayList108 = new ArrayList(1);
        arrayList108.add((Object)"LU");
        hashMap.put((Object)352, (Object)arrayList108);
        ArrayList arrayList109 = new ArrayList(1);
        arrayList109.add((Object)"IE");
        hashMap.put((Object)353, (Object)arrayList109);
        ArrayList arrayList110 = new ArrayList(1);
        arrayList110.add((Object)"IS");
        hashMap.put((Object)354, (Object)arrayList110);
        ArrayList arrayList111 = new ArrayList(1);
        arrayList111.add((Object)"AL");
        hashMap.put((Object)355, (Object)arrayList111);
        ArrayList arrayList112 = new ArrayList(1);
        arrayList112.add((Object)"MT");
        hashMap.put((Object)356, (Object)arrayList112);
        ArrayList arrayList113 = new ArrayList(1);
        arrayList113.add((Object)"CY");
        hashMap.put((Object)357, (Object)arrayList113);
        ArrayList arrayList114 = new ArrayList(2);
        arrayList114.add((Object)"FI");
        arrayList114.add((Object)"AX");
        hashMap.put((Object)358, (Object)arrayList114);
        ArrayList arrayList115 = new ArrayList(1);
        arrayList115.add((Object)"BG");
        hashMap.put((Object)359, (Object)arrayList115);
        ArrayList arrayList116 = new ArrayList(1);
        arrayList116.add((Object)"LT");
        hashMap.put((Object)370, (Object)arrayList116);
        ArrayList arrayList117 = new ArrayList(1);
        arrayList117.add((Object)"LV");
        hashMap.put((Object)371, (Object)arrayList117);
        ArrayList arrayList118 = new ArrayList(1);
        arrayList118.add((Object)"EE");
        hashMap.put((Object)372, (Object)arrayList118);
        ArrayList arrayList119 = new ArrayList(1);
        arrayList119.add((Object)"MD");
        hashMap.put((Object)373, (Object)arrayList119);
        ArrayList arrayList120 = new ArrayList(1);
        arrayList120.add((Object)"AM");
        hashMap.put((Object)374, (Object)arrayList120);
        ArrayList arrayList121 = new ArrayList(1);
        arrayList121.add((Object)"BY");
        hashMap.put((Object)375, (Object)arrayList121);
        ArrayList arrayList122 = new ArrayList(1);
        arrayList122.add((Object)"AD");
        hashMap.put((Object)376, (Object)arrayList122);
        ArrayList arrayList123 = new ArrayList(1);
        arrayList123.add((Object)"MC");
        hashMap.put((Object)377, (Object)arrayList123);
        ArrayList arrayList124 = new ArrayList(1);
        arrayList124.add((Object)"SM");
        hashMap.put((Object)378, (Object)arrayList124);
        ArrayList arrayList125 = new ArrayList(1);
        arrayList125.add((Object)"UA");
        hashMap.put((Object)380, (Object)arrayList125);
        ArrayList arrayList126 = new ArrayList(1);
        arrayList126.add((Object)"RS");
        hashMap.put((Object)381, (Object)arrayList126);
        ArrayList arrayList127 = new ArrayList(1);
        arrayList127.add((Object)"ME");
        hashMap.put((Object)382, (Object)arrayList127);
        ArrayList arrayList128 = new ArrayList(1);
        arrayList128.add((Object)"HR");
        hashMap.put((Object)385, (Object)arrayList128);
        ArrayList arrayList129 = new ArrayList(1);
        arrayList129.add((Object)"SI");
        hashMap.put((Object)386, (Object)arrayList129);
        ArrayList arrayList130 = new ArrayList(1);
        arrayList130.add((Object)"BA");
        hashMap.put((Object)387, (Object)arrayList130);
        ArrayList arrayList131 = new ArrayList(1);
        arrayList131.add((Object)"MK");
        hashMap.put((Object)389, (Object)arrayList131);
        ArrayList arrayList132 = new ArrayList(1);
        arrayList132.add((Object)"CZ");
        hashMap.put((Object)420, (Object)arrayList132);
        ArrayList arrayList133 = new ArrayList(1);
        arrayList133.add((Object)"SK");
        hashMap.put((Object)421, (Object)arrayList133);
        ArrayList arrayList134 = new ArrayList(1);
        arrayList134.add((Object)"LI");
        hashMap.put((Object)423, (Object)arrayList134);
        ArrayList arrayList135 = new ArrayList(1);
        arrayList135.add((Object)"FK");
        hashMap.put((Object)500, (Object)arrayList135);
        ArrayList arrayList136 = new ArrayList(1);
        arrayList136.add((Object)"BZ");
        hashMap.put((Object)501, (Object)arrayList136);
        ArrayList arrayList137 = new ArrayList(1);
        arrayList137.add((Object)"GT");
        hashMap.put((Object)502, (Object)arrayList137);
        ArrayList arrayList138 = new ArrayList(1);
        arrayList138.add((Object)"SV");
        hashMap.put((Object)503, (Object)arrayList138);
        ArrayList arrayList139 = new ArrayList(1);
        arrayList139.add((Object)"HN");
        hashMap.put((Object)504, (Object)arrayList139);
        ArrayList arrayList140 = new ArrayList(1);
        arrayList140.add((Object)"NI");
        hashMap.put((Object)505, (Object)arrayList140);
        ArrayList arrayList141 = new ArrayList(1);
        arrayList141.add((Object)"CR");
        hashMap.put((Object)506, (Object)arrayList141);
        ArrayList arrayList142 = new ArrayList(1);
        arrayList142.add((Object)"PA");
        hashMap.put((Object)507, (Object)arrayList142);
        ArrayList arrayList143 = new ArrayList(1);
        arrayList143.add((Object)"PM");
        hashMap.put((Object)508, (Object)arrayList143);
        ArrayList arrayList144 = new ArrayList(1);
        arrayList144.add((Object)"HT");
        hashMap.put((Object)509, (Object)arrayList144);
        ArrayList arrayList145 = new ArrayList(3);
        arrayList145.add((Object)"GP");
        arrayList145.add((Object)"BL");
        arrayList145.add((Object)"MF");
        hashMap.put((Object)590, (Object)arrayList145);
        ArrayList arrayList146 = new ArrayList(1);
        arrayList146.add((Object)"BO");
        hashMap.put((Object)591, (Object)arrayList146);
        ArrayList arrayList147 = new ArrayList(1);
        arrayList147.add((Object)"GY");
        hashMap.put((Object)592, (Object)arrayList147);
        ArrayList arrayList148 = new ArrayList(1);
        arrayList148.add((Object)"EC");
        hashMap.put((Object)593, (Object)arrayList148);
        ArrayList arrayList149 = new ArrayList(1);
        arrayList149.add((Object)"GF");
        hashMap.put((Object)594, (Object)arrayList149);
        ArrayList arrayList150 = new ArrayList(1);
        arrayList150.add((Object)"PY");
        hashMap.put((Object)595, (Object)arrayList150);
        ArrayList arrayList151 = new ArrayList(1);
        arrayList151.add((Object)"MQ");
        hashMap.put((Object)596, (Object)arrayList151);
        ArrayList arrayList152 = new ArrayList(1);
        arrayList152.add((Object)"SR");
        hashMap.put((Object)597, (Object)arrayList152);
        ArrayList arrayList153 = new ArrayList(1);
        arrayList153.add((Object)"UY");
        hashMap.put((Object)598, (Object)arrayList153);
        ArrayList arrayList154 = new ArrayList(2);
        arrayList154.add((Object)"CW");
        arrayList154.add((Object)"BQ");
        hashMap.put((Object)599, (Object)arrayList154);
        ArrayList arrayList155 = new ArrayList(1);
        arrayList155.add((Object)"TL");
        hashMap.put((Object)670, (Object)arrayList155);
        ArrayList arrayList156 = new ArrayList(1);
        arrayList156.add((Object)"NF");
        hashMap.put((Object)672, (Object)arrayList156);
        ArrayList arrayList157 = new ArrayList(1);
        arrayList157.add((Object)"BN");
        hashMap.put((Object)673, (Object)arrayList157);
        ArrayList arrayList158 = new ArrayList(1);
        arrayList158.add((Object)"NR");
        hashMap.put((Object)674, (Object)arrayList158);
        ArrayList arrayList159 = new ArrayList(1);
        arrayList159.add((Object)"PG");
        hashMap.put((Object)675, (Object)arrayList159);
        ArrayList arrayList160 = new ArrayList(1);
        arrayList160.add((Object)"TO");
        hashMap.put((Object)676, (Object)arrayList160);
        ArrayList arrayList161 = new ArrayList(1);
        arrayList161.add((Object)"SB");
        hashMap.put((Object)677, (Object)arrayList161);
        ArrayList arrayList162 = new ArrayList(1);
        arrayList162.add((Object)"VU");
        hashMap.put((Object)678, (Object)arrayList162);
        ArrayList arrayList163 = new ArrayList(1);
        arrayList163.add((Object)"FJ");
        hashMap.put((Object)679, (Object)arrayList163);
        ArrayList arrayList164 = new ArrayList(1);
        arrayList164.add((Object)"PW");
        hashMap.put((Object)680, (Object)arrayList164);
        ArrayList arrayList165 = new ArrayList(1);
        arrayList165.add((Object)"WF");
        hashMap.put((Object)681, (Object)arrayList165);
        ArrayList arrayList166 = new ArrayList(1);
        arrayList166.add((Object)"CK");
        hashMap.put((Object)682, (Object)arrayList166);
        ArrayList arrayList167 = new ArrayList(1);
        arrayList167.add((Object)"NU");
        hashMap.put((Object)683, (Object)arrayList167);
        ArrayList arrayList168 = new ArrayList(1);
        arrayList168.add((Object)"WS");
        hashMap.put((Object)685, (Object)arrayList168);
        ArrayList arrayList169 = new ArrayList(1);
        arrayList169.add((Object)"KI");
        hashMap.put((Object)686, (Object)arrayList169);
        ArrayList arrayList170 = new ArrayList(1);
        arrayList170.add((Object)"NC");
        hashMap.put((Object)687, (Object)arrayList170);
        ArrayList arrayList171 = new ArrayList(1);
        arrayList171.add((Object)"TV");
        hashMap.put((Object)688, (Object)arrayList171);
        ArrayList arrayList172 = new ArrayList(1);
        arrayList172.add((Object)"PF");
        hashMap.put((Object)689, (Object)arrayList172);
        ArrayList arrayList173 = new ArrayList(1);
        arrayList173.add((Object)"TK");
        hashMap.put((Object)690, (Object)arrayList173);
        ArrayList arrayList174 = new ArrayList(1);
        arrayList174.add((Object)"FM");
        hashMap.put((Object)691, (Object)arrayList174);
        ArrayList arrayList175 = new ArrayList(1);
        arrayList175.add((Object)"MH");
        hashMap.put((Object)692, (Object)arrayList175);
        ArrayList arrayList176 = new ArrayList(1);
        arrayList176.add((Object)"001");
        hashMap.put((Object)800, (Object)arrayList176);
        ArrayList arrayList177 = new ArrayList(1);
        arrayList177.add((Object)"001");
        hashMap.put((Object)808, (Object)arrayList177);
        ArrayList arrayList178 = new ArrayList(1);
        arrayList178.add((Object)"KP");
        hashMap.put((Object)850, (Object)arrayList178);
        ArrayList arrayList179 = new ArrayList(1);
        arrayList179.add((Object)"HK");
        hashMap.put((Object)852, (Object)arrayList179);
        ArrayList arrayList180 = new ArrayList(1);
        arrayList180.add((Object)"MO");
        hashMap.put((Object)853, (Object)arrayList180);
        ArrayList arrayList181 = new ArrayList(1);
        arrayList181.add((Object)"KH");
        hashMap.put((Object)855, (Object)arrayList181);
        ArrayList arrayList182 = new ArrayList(1);
        arrayList182.add((Object)"LA");
        hashMap.put((Object)856, (Object)arrayList182);
        ArrayList arrayList183 = new ArrayList(1);
        arrayList183.add((Object)"001");
        hashMap.put((Object)870, (Object)arrayList183);
        ArrayList arrayList184 = new ArrayList(1);
        arrayList184.add((Object)"001");
        hashMap.put((Object)878, (Object)arrayList184);
        ArrayList arrayList185 = new ArrayList(1);
        arrayList185.add((Object)"BD");
        hashMap.put((Object)880, (Object)arrayList185);
        ArrayList arrayList186 = new ArrayList(1);
        arrayList186.add((Object)"001");
        hashMap.put((Object)881, (Object)arrayList186);
        ArrayList arrayList187 = new ArrayList(1);
        arrayList187.add((Object)"001");
        hashMap.put((Object)882, (Object)arrayList187);
        ArrayList arrayList188 = new ArrayList(1);
        arrayList188.add((Object)"001");
        hashMap.put((Object)883, (Object)arrayList188);
        ArrayList arrayList189 = new ArrayList(1);
        arrayList189.add((Object)"TW");
        hashMap.put((Object)886, (Object)arrayList189);
        ArrayList arrayList190 = new ArrayList(1);
        arrayList190.add((Object)"001");
        hashMap.put((Object)888, (Object)arrayList190);
        ArrayList arrayList191 = new ArrayList(1);
        arrayList191.add((Object)"MV");
        hashMap.put((Object)960, (Object)arrayList191);
        ArrayList arrayList192 = new ArrayList(1);
        arrayList192.add((Object)"LB");
        hashMap.put((Object)961, (Object)arrayList192);
        ArrayList arrayList193 = new ArrayList(1);
        arrayList193.add((Object)"JO");
        hashMap.put((Object)962, (Object)arrayList193);
        ArrayList arrayList194 = new ArrayList(1);
        arrayList194.add((Object)"SY");
        hashMap.put((Object)963, (Object)arrayList194);
        ArrayList arrayList195 = new ArrayList(1);
        arrayList195.add((Object)"IQ");
        hashMap.put((Object)964, (Object)arrayList195);
        ArrayList arrayList196 = new ArrayList(1);
        arrayList196.add((Object)"KW");
        hashMap.put((Object)965, (Object)arrayList196);
        ArrayList arrayList197 = new ArrayList(1);
        arrayList197.add((Object)"SA");
        hashMap.put((Object)966, (Object)arrayList197);
        ArrayList arrayList198 = new ArrayList(1);
        arrayList198.add((Object)"YE");
        hashMap.put((Object)967, (Object)arrayList198);
        ArrayList arrayList199 = new ArrayList(1);
        arrayList199.add((Object)"OM");
        hashMap.put((Object)968, (Object)arrayList199);
        ArrayList arrayList200 = new ArrayList(1);
        arrayList200.add((Object)"PS");
        hashMap.put((Object)970, (Object)arrayList200);
        ArrayList arrayList201 = new ArrayList(1);
        arrayList201.add((Object)"AE");
        hashMap.put((Object)971, (Object)arrayList201);
        ArrayList arrayList202 = new ArrayList(1);
        arrayList202.add((Object)"IL");
        hashMap.put((Object)972, (Object)arrayList202);
        ArrayList arrayList203 = new ArrayList(1);
        arrayList203.add((Object)"BH");
        hashMap.put((Object)973, (Object)arrayList203);
        ArrayList arrayList204 = new ArrayList(1);
        arrayList204.add((Object)"QA");
        hashMap.put((Object)974, (Object)arrayList204);
        ArrayList arrayList205 = new ArrayList(1);
        arrayList205.add((Object)"BT");
        hashMap.put((Object)975, (Object)arrayList205);
        ArrayList arrayList206 = new ArrayList(1);
        arrayList206.add((Object)"MN");
        hashMap.put((Object)976, (Object)arrayList206);
        ArrayList arrayList207 = new ArrayList(1);
        arrayList207.add((Object)"NP");
        hashMap.put((Object)977, (Object)arrayList207);
        ArrayList arrayList208 = new ArrayList(1);
        arrayList208.add((Object)"001");
        hashMap.put((Object)979, (Object)arrayList208);
        ArrayList arrayList209 = new ArrayList(1);
        arrayList209.add((Object)"TJ");
        hashMap.put((Object)992, (Object)arrayList209);
        ArrayList arrayList210 = new ArrayList(1);
        arrayList210.add((Object)"TM");
        hashMap.put((Object)993, (Object)arrayList210);
        ArrayList arrayList211 = new ArrayList(1);
        arrayList211.add((Object)"AZ");
        hashMap.put((Object)994, (Object)arrayList211);
        ArrayList arrayList212 = new ArrayList(1);
        arrayList212.add((Object)"GE");
        hashMap.put((Object)995, (Object)arrayList212);
        ArrayList arrayList213 = new ArrayList(1);
        arrayList213.add((Object)"KG");
        hashMap.put((Object)996, (Object)arrayList213);
        ArrayList arrayList214 = new ArrayList(1);
        arrayList214.add((Object)"UZ");
        hashMap.put((Object)998, (Object)arrayList214);
        return hashMap;
    }
}

